/**
 * 기본 뷰 정의
 * 관리자가 "기본 뷰 생성하기" 클릭 시 일괄 생성
 */
export interface DefaultViewDef {
  name: string;
  view_type: string;
  icon: string;
  description: string;
  filter_config: Record<string, unknown> | null;
  schema_map: Record<string, string> | null;
  sort_order: number;
}

export const DEFAULT_VIEWS: DefaultViewDef[] = [
  {
    name: '내 캘린더',
    view_type: 'calendar',
    icon: '\uD83D\uDCC5',
    description: '일정을 달력으로 한눈에',
    filter_config: { domain: 'schedule' },
    schema_map: { title: 'title', date: 'date', time: 'time' },
    sort_order: 1,
  },
  {
    name: '할 일 보드',
    view_type: 'task',
    icon: '\uD83D\uDCCB',
    description: '할 일을 상태별로 정리',
    filter_config: { domain: 'task' },
    schema_map: { title: 'title', status: 'status', due: 'due', priority: 'priority' },
    sort_order: 2,
  },
  {
    name: '습관 트래커',
    view_type: 'heatmap',
    icon: '\uD83D\uDD25',
    description: '습관 기록을 한눈에',
    filter_config: { domain: 'habit' },
    schema_map: { date: 'date', value: 'frequency' },
    sort_order: 3,
  },
  {
    name: '지식 그래프',
    view_type: 'knowledge_graph',
    icon: '\uD83D\uDD78\uFE0F',
    description: '지식 간의 연결을 시각화',
    filter_config: { domain: 'knowledge' },
    schema_map: { title: 'title' },
    sort_order: 4,
  },
  {
    name: '아이디어 맵',
    view_type: 'mindmap',
    icon: '\uD83D\uDCA1',
    description: '아이디어를 가지치기로',
    filter_config: { domain: 'idea' },
    schema_map: { title: 'title', category: 'category' },
    sort_order: 5,
  },
  {
    name: '감정 일기',
    view_type: 'journal',
    icon: '\uD83D\uDCD3',
    description: '감정 기록을 일기 형태로',
    filter_config: { domain: 'emotion' },
    schema_map: { date: 'date', mood: 'mood', content: 'content' },
    sort_order: 6,
  },
  {
    name: '지출 차트',
    view_type: 'chart',
    icon: '\uD83D\uDCCA',
    description: '지출 내역을 차트로',
    filter_config: { domain: 'finance' },
    schema_map: { amount: 'amount', category: 'category', date: 'date' },
    sort_order: 7,
  },
  {
    name: '타임라인',
    view_type: 'timeline',
    icon: '\u23F3',
    description: '모든 데이터를 시간순으로',
    filter_config: null,
    schema_map: { date: 'date', title: 'title' },
    sort_order: 8,
  },
  {
    name: '플래시카드',
    view_type: 'flashcard',
    icon: '\uD83C\uDCCF',
    description: '지식을 카드로 학습',
    filter_config: { domain: 'knowledge' },
    schema_map: { question: 'question', answer: 'answer' },
    sort_order: 9,
  },
  {
    name: '사전',
    view_type: 'dictionary',
    icon: '\uD83D\uDCD6',
    description: '용어와 정의를 사전 형태로',
    filter_config: { domain: 'knowledge' },
    schema_map: { term: 'term', definition: 'definition' },
    sort_order: 10,
  },
  {
    name: '문서',
    view_type: 'document',
    icon: '\uD83D\uDCC4',
    description: '데이터를 구조화된 문서로',
    filter_config: null,
    schema_map: { title: 'title' },
    sort_order: 11,
  },
  {
    name: '전체 데이터',
    view_type: 'table',
    icon: '\uD83D\uDDC2\uFE0F',
    description: '모든 데이터를 표 형태로',
    filter_config: null,
    schema_map: null,
    sort_order: 12,
  },
  {
    name: 'PDF 리더',
    view_type: 'pdf',
    icon: '\uD83D\uDCC3',
    description: '문서를 원본·요약·목차·인사이트로',
    filter_config: { source_type: 'pdf' },
    schema_map: { file_url: 'file_url', extracted_text: 'extracted_text', summary: 'summary' },
    sort_order: 13,
  },
  {
    name: '내 강의',
    view_type: 'lecture',
    icon: '\uD83C\uDF93',
    description: '데이터로 나만의 강의를 만들기',
    filter_config: { domain: 'education' },
    schema_map: { title: 'title', content: 'content', order: 'order' },
    sort_order: 14,
  },
  {
    name: '내 프로필',
    view_type: 'profile',
    icon: '\uD83D\uDC64',
    description: '나의 프로필과 공개 데이터',
    filter_config: null,
    schema_map: null,
    sort_order: 15,
  },
  {
    name: '내 지도',
    view_type: 'map',
    icon: '\uD83D\uDCCD',
    description: '약속 장소를 지도에서 한눈에',
    filter_config: null,
    schema_map: { title: 'title', location: 'location', date: 'date' },
    sort_order: 16,
  },
  {
    name: '개발 세션',
    view_type: 'code',
    icon: '\uD83D\uDCBB',
    description: '개발 과정을 데이터로',
    filter_config: { domain: 'development' },
    schema_map: { title: 'title', action_type: 'action_type', files_changed: 'files_changed' },
    sort_order: 17,
  },
  {
    name: '터미널',
    view_type: 'terminal',
    icon: '\uD83D\uDDA5\uFE0F',
    description: '개발 로그를 터미널 형태로',
    filter_config: { source_type: 'dev_tool' },
    schema_map: { title: 'title', date: 'date' },
    sort_order: 18,
  },
  {
    name: 'AI 개발 대화',
    view_type: 'ai_dev',
    icon: '\uD83E\uDD16',
    description: 'AI와의 개발 대화 기록',
    filter_config: { domain: 'development' },
    schema_map: { title: 'title', date: 'date' },
    sort_order: 19,
  },
];
