import type { TableSchema } from '@/types/admin';

/**
 * DB 에디터용 테이블 스키마 정의
 * 실제 Supabase 테이블 구조를 반영
 */
export const TABLE_SCHEMAS: TableSchema[] = [
  {
    name: 'profiles',
    label: '회원 프로필',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'email', type: 'text', label: '이메일', editable: false },
      { name: 'display_name', type: 'text', label: '이름', editable: true },
      { name: 'handle', type: 'text', label: '핸들', editable: true },
      { name: 'avatar_url', type: 'text', label: '프로필 이미지', editable: true },
      { name: 'bio', type: 'text', label: '소개', editable: true },
      { name: 'language', type: 'text', label: '언어', editable: true },
      { name: 'verified', type: 'boolean', label: '인증', editable: true },
      { name: 'user_level', type: 'enum', label: '레벨', editable: true, options: ['unknown', 'basic', 'intermediate', 'expert'] },
      { name: 'created_at', type: 'timestamp', label: '가입일', editable: false },
      { name: 'updated_at', type: 'timestamp', label: '수정일', editable: false },
    ],
  },
  {
    name: 'data_nodes',
    label: '데이터 노드',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'user_id', type: 'uuid', label: '회원', editable: false, fkTable: 'profiles', fkDisplay: 'display_name' },
      { name: 'group_id', type: 'uuid', label: '그룹', editable: true, fkTable: 'groups', fkDisplay: 'name' },
      { name: 'message_id', type: 'uuid', label: '메시지', editable: false, fkTable: 'messages' },
      { name: 'is_admin_node', type: 'boolean', label: '관리자 노드', editable: true },
      { name: 'domain', type: 'enum', label: '도메인', editable: true, options: ['schedule', 'task', 'habit', 'knowledge', 'idea', 'relation', 'emotion', 'finance', 'product', 'broadcast', 'education', 'media', 'location', 'unresolved'] },
      { name: 'source_type', type: 'text', label: '소스 타입', editable: true },
      { name: 'confidence', type: 'enum', label: '신뢰도', editable: true, options: ['high', 'medium', 'low'] },
      { name: 'resolution', type: 'text', label: '해결', editable: true },
      { name: 'visibility', type: 'enum', label: '공개', editable: true, options: ['private', 'link', 'public'] },
      { name: 'view_hint', type: 'text', label: '뷰 힌트', editable: true },
      { name: 'domain_data', type: 'json', label: '도메인 데이터', editable: true, hidden: true },
      { name: 'system_tags', type: 'array', label: '태그', editable: true },
      { name: 'raw', type: 'text', label: '원본', editable: true },
      { name: 'storage_tier', type: 'enum', label: '스토리지', editable: true, options: ['hot', 'warm', 'cold'] },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
      { name: 'updated_at', type: 'timestamp', label: '수정일', editable: false },
    ],
  },
  {
    name: 'messages',
    label: '메시지',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'user_id', type: 'uuid', label: '회원', editable: false, fkTable: 'profiles', fkDisplay: 'display_name' },
      { name: 'group_id', type: 'uuid', label: '그룹', editable: false, fkTable: 'groups', fkDisplay: 'name' },
      { name: 'role', type: 'enum', label: '역할', editable: false, options: ['user', 'assistant', 'system'] },
      { name: 'raw', type: 'text', label: '내용', editable: true },
      { name: 'type', type: 'text', label: '타입', editable: true },
      { name: 'pair_id', type: 'uuid', label: '페어', editable: false },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'sections',
    label: '섹션',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'node_id', type: 'uuid', label: '노드', editable: false, fkTable: 'data_nodes' },
      { name: 'heading', type: 'text', label: '제목', editable: true },
      { name: 'order_idx', type: 'integer', label: '순서', editable: true },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'sentences',
    label: '문장',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'section_id', type: 'uuid', label: '섹션', editable: false, fkTable: 'sections' },
      { name: 'node_id', type: 'uuid', label: '노드', editable: false, fkTable: 'data_nodes' },
      { name: 'text', type: 'text', label: '텍스트', editable: true },
      { name: 'order_idx', type: 'integer', label: '순서', editable: true },
      { name: 'embed_status', type: 'text', label: '임베딩', editable: false },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'triples',
    label: '트리플',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'node_id', type: 'uuid', label: '노드', editable: false, fkTable: 'data_nodes' },
      { name: 'section_id', type: 'uuid', label: '섹션', editable: true, fkTable: 'sections' },
      { name: 'subject', type: 'text', label: '주어', editable: true, required: true },
      { name: 'predicate', type: 'enum', label: '서술어', editable: true, required: true, options: ['is_a', 'part_of', 'causes', 'derived_from', 'related_to', 'opposite_of', 'requires', 'example_of', 'involves', 'located_at', 'occurs_at'] },
      { name: 'object', type: 'text', label: '목적어', editable: true, required: true },
      { name: 'source_level', type: 'text', label: '소스 레벨', editable: true },
      { name: 'source_type', type: 'text', label: '소스 타입', editable: true },
      { name: 'confidence', type: 'enum', label: '신뢰도', editable: true, options: ['high', 'medium', 'low'] },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'triple_sentence_sources',
    label: '트리플-문장 연결',
    columns: [
      { name: 'triple_id', type: 'uuid', label: '트리플', editable: false, fkTable: 'triples' },
      { name: 'sentence_id', type: 'uuid', label: '문장', editable: false, fkTable: 'sentences' },
    ],
  },
  {
    name: 'node_relations',
    label: '노드 관계',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'source_node_id', type: 'uuid', label: '소스', editable: true, fkTable: 'data_nodes' },
      { name: 'target_node_id', type: 'uuid', label: '타겟', editable: true, fkTable: 'data_nodes' },
      { name: 'relation_type', type: 'text', label: '관계 타입', editable: true },
      { name: 'weight', type: 'float', label: '가중치', editable: true },
      { name: 'source', type: 'text', label: '출처', editable: true },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'groups',
    label: '그룹',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'name', type: 'text', label: '이름', editable: true, required: true },
      { name: 'description', type: 'text', label: '설명', editable: true },
      { name: 'owner_id', type: 'uuid', label: '소유자', editable: false, fkTable: 'profiles', fkDisplay: 'display_name' },
      { name: 'visibility', type: 'enum', label: '공개', editable: true, options: ['private', 'link', 'public'] },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'group_members',
    label: '그룹 멤버',
    columns: [
      { name: 'group_id', type: 'uuid', label: '그룹', editable: false, fkTable: 'groups', fkDisplay: 'name' },
      { name: 'user_id', type: 'uuid', label: '회원', editable: false, fkTable: 'profiles', fkDisplay: 'display_name' },
      { name: 'role', type: 'text', label: '역할', editable: true },
      { name: 'joined_at', type: 'timestamp', label: '가입일', editable: false },
    ],
  },
  {
    name: 'group_invites',
    label: '그룹 초대',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'group_id', type: 'uuid', label: '그룹', editable: false, fkTable: 'groups', fkDisplay: 'name' },
      { name: 'token', type: 'text', label: '토큰', editable: false },
      { name: 'created_by', type: 'uuid', label: '생성자', editable: false, fkTable: 'profiles' },
      { name: 'expires_at', type: 'timestamp', label: '만료일', editable: true },
      { name: 'used_at', type: 'timestamp', label: '사용일', editable: false },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'personas',
    label: '페르소나',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'user_id', type: 'uuid', label: '회원', editable: false, fkTable: 'profiles', fkDisplay: 'display_name' },
      { name: 'handle', type: 'text', label: '핸들', editable: true },
      { name: 'display_name', type: 'text', label: '이름', editable: true },
      { name: 'bio', type: 'text', label: '소개', editable: true },
      { name: 'is_default', type: 'boolean', label: '기본', editable: true },
      { name: 'visibility', type: 'enum', label: '공개', editable: true, options: ['private', 'link', 'public'] },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'persona_node_visibility',
    label: '페르소나 노드 공개',
    columns: [
      { name: 'persona_id', type: 'uuid', label: '페르소나', editable: false, fkTable: 'personas' },
      { name: 'node_id', type: 'uuid', label: '노드', editable: false, fkTable: 'data_nodes' },
      { name: 'is_visible', type: 'boolean', label: '공개', editable: true },
    ],
  },
  {
    name: 'persona_follows',
    label: '팔로우',
    columns: [
      { name: 'follower_persona_id', type: 'uuid', label: '팔로워', editable: false, fkTable: 'personas' },
      { name: 'following_persona_id', type: 'uuid', label: '팔로잉', editable: false, fkTable: 'personas' },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'saved_views',
    label: '저장된 뷰',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'user_id', type: 'uuid', label: '회원', editable: false, fkTable: 'profiles', fkDisplay: 'display_name' },
      { name: 'group_id', type: 'uuid', label: '그룹', editable: true, fkTable: 'groups', fkDisplay: 'name' },
      { name: 'name', type: 'text', label: '이름', editable: true, required: true },
      { name: 'view_type', type: 'text', label: '뷰 타입', editable: true },
      { name: 'filter_config', type: 'json', label: '필터', editable: true },
      { name: 'layout_config', type: 'json', label: '레이아웃', editable: true },
      { name: 'custom_code', type: 'text', label: '커스텀 코드', editable: true, hidden: true },
      { name: 'visibility', type: 'enum', label: '공개', editable: true, options: ['private', 'link', 'public'] },
      { name: 'is_default', type: 'boolean', label: '기본 뷰', editable: true },
      { name: 'description', type: 'text', label: '설명', editable: true },
      { name: 'icon', type: 'text', label: '아이콘', editable: true },
      { name: 'schema_map', type: 'json', label: '스키마 매핑', editable: true },
      { name: 'sort_order', type: 'integer', label: '정렬 순서', editable: true },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
      { name: 'updated_at', type: 'timestamp', label: '수정일', editable: false },
    ],
  },
  {
    name: 'view_members',
    label: '뷰 멤버',
    columns: [
      { name: 'view_id', type: 'uuid', label: '뷰', editable: false, fkTable: 'saved_views' },
      { name: 'user_id', type: 'uuid', label: '회원', editable: false, fkTable: 'profiles', fkDisplay: 'display_name' },
      { name: 'role', type: 'text', label: '역할', editable: true },
      { name: 'joined_at', type: 'timestamp', label: '가입일', editable: false },
    ],
  },
  {
    name: 'message_events',
    label: '메시지 이벤트',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'message_id', type: 'uuid', label: '메시지', editable: false, fkTable: 'messages' },
      { name: 'user_id', type: 'uuid', label: '회원', editable: false, fkTable: 'profiles' },
      { name: 'event_type', type: 'text', label: '이벤트', editable: false },
      { name: 'metadata', type: 'json', label: '메타데이터', editable: false },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'unresolved_entities',
    label: '미해결 엔티티',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'user_id', type: 'uuid', label: '회원', editable: false, fkTable: 'profiles' },
      { name: 'raw_text', type: 'text', label: '원본', editable: true },
      { name: 'context_snippet', type: 'text', label: '맥락', editable: true },
      { name: 'placeholder_node_id', type: 'uuid', label: '임시 노드', editable: true, fkTable: 'data_nodes' },
      { name: 'resolved_node_id', type: 'uuid', label: '해결 노드', editable: true, fkTable: 'data_nodes' },
      { name: 'resolution_status', type: 'text', label: '상태', editable: true },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
      { name: 'resolved_at', type: 'timestamp', label: '해결일', editable: false },
    ],
  },
  {
    name: 'user_node_refs',
    label: '관리자 노드 참조',
    columns: [
      { name: 'user_id', type: 'uuid', label: '회원', editable: false, fkTable: 'profiles' },
      { name: 'node_id', type: 'uuid', label: '노드', editable: false, fkTable: 'data_nodes' },
      { name: 'added_at', type: 'timestamp', label: '추가일', editable: false },
    ],
  },
  {
    name: 'subscriptions',
    label: '구독',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'user_id', type: 'uuid', label: '회원', editable: false, fkTable: 'profiles', fkDisplay: 'display_name' },
      { name: 'plan', type: 'enum', label: '플랜', editable: true, options: ['free', 'pro', 'team'] },
      { name: 'token_limit', type: 'integer', label: '토큰 한도', editable: true },
      { name: 'current_period_start', type: 'timestamp', label: '시작일', editable: false },
      { name: 'current_period_end', type: 'timestamp', label: '종료일', editable: false },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'token_usage',
    label: '토큰 사용량',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'user_id', type: 'uuid', label: '회원', editable: false, fkTable: 'profiles' },
      { name: 'operation', type: 'text', label: '작업', editable: false },
      { name: 'tokens_used', type: 'integer', label: '사용량', editable: false },
      { name: 'llm_tokens_actual', type: 'integer', label: 'LLM 토큰', editable: false },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'verification_requests',
    label: '검증 요청',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'node_id', type: 'uuid', label: '노드', editable: false, fkTable: 'data_nodes' },
      { name: 'triple_id', type: 'uuid', label: '트리플', editable: false, fkTable: 'triples' },
      { name: 'reason', type: 'text', label: '사유', editable: true },
      { name: 'status', type: 'enum', label: '상태', editable: true, options: ['open', 'resolved', 'escalated'] },
      { name: 'vote_approve', type: 'integer', label: '승인', editable: false },
      { name: 'vote_reject', type: 'integer', label: '거부', editable: false },
      { name: 'vote_unsure', type: 'integer', label: '보류', editable: false },
      { name: 'threshold', type: 'integer', label: '임계값', editable: true },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
      { name: 'resolved_at', type: 'timestamp', label: '해결일', editable: false },
    ],
  },
  {
    name: 'verification_votes',
    label: '검증 투표',
    columns: [
      { name: 'request_id', type: 'uuid', label: '요청', editable: false, fkTable: 'verification_requests' },
      { name: 'user_id', type: 'uuid', label: '회원', editable: false, fkTable: 'profiles' },
      { name: 'vote', type: 'enum', label: '투표', editable: false, options: ['approve', 'reject', 'unsure'] },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'api_audit_log',
    label: '감사 로그',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'admin_id', type: 'uuid', label: '관리자', editable: false, fkTable: 'profiles', fkDisplay: 'display_name' },
      { name: 'action', type: 'text', label: '액션', editable: false },
      { name: 'target_type', type: 'text', label: '대상 타입', editable: false },
      { name: 'target_id', type: 'text', label: '대상 ID', editable: false },
      { name: 'metadata', type: 'json', label: '메타데이터', editable: false },
      { name: 'ip_address', type: 'text', label: 'IP', editable: false },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'api_cost_log',
    label: 'API 비용 로그',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'operation', type: 'text', label: '작업', editable: false },
      { name: 'model', type: 'text', label: '모델', editable: false },
      { name: 'tokens', type: 'integer', label: '토큰', editable: false },
      { name: 'cost_usd', type: 'float', label: '비용(USD)', editable: false },
      { name: 'user_id', type: 'uuid', label: '회원', editable: false, fkTable: 'profiles' },
      { name: 'node_id', type: 'uuid', label: '노드', editable: false, fkTable: 'data_nodes' },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'chat_rooms',
    label: '채팅방',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'chat_room_members',
    label: '채팅방 멤버',
    columns: [
      { name: 'room_id', type: 'uuid', label: '채팅방', editable: false, fkTable: 'chat_rooms' },
      { name: 'user_id', type: 'uuid', label: '회원', editable: false, fkTable: 'profiles', fkDisplay: 'display_name' },
    ],
  },
  {
    name: 'chat_messages',
    label: '채팅 메시지',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'room_id', type: 'uuid', label: '채팅방', editable: false, fkTable: 'chat_rooms' },
      { name: 'sender_id', type: 'uuid', label: '발신자', editable: false, fkTable: 'profiles', fkDisplay: 'display_name' },
      { name: 'content', type: 'text', label: '내용', editable: true },
      { name: 'node_id', type: 'uuid', label: '노드', editable: true, fkTable: 'data_nodes' },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'market_items',
    label: '마켓 상품',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'seller_id', type: 'uuid', label: '판매자', editable: false, fkTable: 'profiles', fkDisplay: 'display_name' },
      { name: 'view_id', type: 'uuid', label: '뷰', editable: true, fkTable: 'saved_views' },
      { name: 'name', type: 'text', label: '이름', editable: true, required: true },
      { name: 'description', type: 'text', label: '설명', editable: true },
      { name: 'price_krw', type: 'integer', label: '가격(원)', editable: true },
      { name: 'thumbnail_url', type: 'text', label: '썸네일', editable: true },
      { name: 'purchase_count', type: 'integer', label: '구매 수', editable: false },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
  {
    name: 'market_purchases',
    label: '마켓 구매',
    defaultSort: 'created_at',
    columns: [
      { name: 'id', type: 'uuid', label: 'ID', editable: false },
      { name: 'item_id', type: 'uuid', label: '상품', editable: false, fkTable: 'market_items' },
      { name: 'buyer_id', type: 'uuid', label: '구매자', editable: false, fkTable: 'profiles', fkDisplay: 'display_name' },
      { name: 'price_paid', type: 'integer', label: '결제 금액', editable: false },
      { name: 'created_at', type: 'timestamp', label: '생성일', editable: false },
    ],
  },
];

/** 테이블명 화이트리스트 */
export const ALLOWED_TABLES = TABLE_SCHEMAS.map(t => t.name);

/** 테이블명으로 스키마 조회 */
export function getTableSchema(name: string): TableSchema | undefined {
  return TABLE_SCHEMAS.find(t => t.name === name);
}
